#cloud-config
locale: en_US
timezone: Europe/Tallinn
hostname: base
users:
  - name: ansible
    groups: wheel
  - name: devops
    groups: wheel
runcmd:
  - ["tailscale", "up", "--auth-key=xxx", "--ssh"]
