#!/usr/bin/env bash
#MISE description="Build disk image from bootc image"
mkdir -p $PWD/output
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v ./config.toml:/config.toml:ro \
    -v ./output:/output \
    -v /var/lib/containers/storage:/var/lib/containers/storage \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --rootfs $ROOTFS
    --type $TYPE \
	--use-librepo=True \
    $REGISTRY_URL/$REGISTRY_USERNAME/$IMAGE_NAME:latest
