#!/usr/bin/env bash
#MISE description="Sign image using cosign"
IMAGE_DIGEST=$(podman image inspect $REGISTRY_URL/$REGISTRY_USERNAME/$IMAGE_NAME:latest --format '{{.Digest}}')
cosign sign --yes $REGISTRY_URL/$REGISTRY_USERNAME/$IMAGE_NAME@$IMAGE_DIGEST
